name: App build
on: push
jobs:
  Build_Artifact:
    runs-on: ubuntu-latest
    steps:
      ## Checkout our repository ###
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Set up our JDK environment
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
      ## Build all our Build Types at once ##
    - name: Build all artifacts
      id: buildAllApks
      uses: eskatos/gradle-command-action@v1.3.3
      with:
        gradle-version: current
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        arguments: assembleRelease
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: Release artifact
        path: app/build/outputs/apk/ourbuildtype/release/app-artifact-*.apk
        retention-days: 1
